### ISSUE TITLE
Player param is never used

### ISSUE THREAD

**Issue by AlexKap23** [Esoham/Tick-Tack-Toe#4]
https://github.com/Esoham/Tick-Tack-Toe/blob/21ce203d3f877e6e59c6ee80e61713a250cfdd53/Tick%20Toe/GameLogic.cs#L61

The parameter that this method accepts is never used in the method's body. Also, this method is called FindBestMove, but it only finds the availabe moved and returns back a random of them. So method name not so accurate.

**Comment by Esoham** [comment]
-Rename FindBestMove to SelectRandomMove to accurately reflect its functionality.
